/* Generated By:JJTree: Do not edit this line. ASTConditionalStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.ast;


public
class ASTConditionalStatement extends SimpleNode {
  public ASTConditionalStatement(int id) {
    super(id);
  }

  public ASTConditionalStatement(Go p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4d73e0ad170112351359a26b9fc036d2 (do not edit this line) */
