/* Generated By:JJTree: Do not edit this line. ASTDeclarationStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.ast;


public
class ASTDeclarationStatement extends SimpleNode {
  public ASTDeclarationStatement(int id) {
    super(id);
  }

  public ASTDeclarationStatement(Go p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed3255eb4105c0d736c573d72e7ddbd1 (do not edit this line) */
