/* Generated By:JJTree: Do not edit this line. ASTfunctionParam.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.ast;


public
class ASTfunctionParam extends SimpleNode {
  public ASTfunctionParam(int id) {
    super(id);
  }

  public ASTfunctionParam(Go p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4ae9ef46723e09b49ec37a1ecf5a51ac (do not edit this line) */
