/* Generated By:JJTree: Do not edit this line. ASTOneOperandOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.ast;


public
class ASTOneOperandOperator extends SimpleNode {
  public ASTOneOperandOperator(int id) {
    super(id);
  }

  public ASTOneOperandOperator(Go p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=df5b448c48022a5aa446a11523d4d3a4 (do not edit this line) */
