/* Generated By:JJTree: Do not edit this line. ASTRelationOperations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.ast;


public
class ASTRelationOperations extends SimpleNode {
  public ASTRelationOperations(int id) {
    super(id);
  }

  public ASTRelationOperations(Go p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=844e0232d716988733d485c66658fbe8 (do not edit this line) */
