/* Generated By:JJTree: Do not edit this line. ASTSwitchExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.ast;


public
class ASTSwitchExpression extends SimpleNode {
  public ASTSwitchExpression(int id) {
    super(id);
  }

  public ASTSwitchExpression(Go p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a092bb1fa8ed50b7deb4f4842c29d1b (do not edit this line) */
