/* Generated By:JJTree: Do not edit this line. ASTStructDec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.ast;


public
class ASTStructDec extends SimpleNode {
  public ASTStructDec(int id) {
    super(id);
  }

  public ASTStructDec(Go p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ebfee8aee3b5a528f5b2269a5ca39e4 (do not edit this line) */
