/* Generated By:JavaCC: Do not edit this line. GoTreeConstants.java Version 5.0 */
package com.bupt.ast;


public interface GoTreeConstants
{
  public int JJTONE_LINE = 0;
  public int JJTSUM = 1;
  public int JJTTERM = 2;
  public int JJTUNARY = 3;
  public int JJTELEMENT = 4;
  public int JJTDECLARATIONSTATEMENT = 5;
  public int JJTTYPE = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTASSIGNMENTOPERATOR = 8;
  public int JJTONEOPERANDOPERATOR = 9;
  public int JJTITERATIONSTATEMENT = 10;
  public int JJTSIMPLESTATEMENT = 11;
  public int JJTCONDITIONALSTATEMENT = 12;
  public int JJTCONDITION = 13;
  public int JJTRELATIONOPERATIONS = 14;
  public int JJTBLOCK = 15;
  public int JJTASSIGNMENTSTATEMENT = 16;
  public int JJTINCREMENT = 17;
  public int JJTOPERAND = 18;
  public int JJTFUNCTIONDECLARATION = 19;
  public int JJTRETURNTYPE = 20;
  public int JJTFUNCTIONBODY = 21;
  public int JJTRETURNSTATEMENT = 22;
  public int JJTPARAMETER = 23;
  public int JJTFUNCTION = 24;
  public int JJTFUNCTIONPARAM = 25;
  public int JJTSWITCHSTATEMENT = 26;
  public int JJTSWITCHEXPRESSION = 27;
  public int JJTSWITCHBODY = 28;
  public int JJTCASE = 29;
  public int JJTSTRUCTDEC = 30;
  public int JJTINSTRUCT = 31;
  public int JJTFUNCALL = 32;
  public int JJTSTATEMENT = 33;
  public int JJTSTATEMENTS = 34;
  public int JJTPROGRAM = 35;
  public int JJTVOID = 36;


  public String[] jjtNodeName = {
    "one_line",
    "sum",
    "term",
    "unary",
    "element",
    "DeclarationStatement",
    "type",
    "Assignment",
    "AssignmentOperator",
    "OneOperandOperator",
    "IterationStatement",
    "SimpleStatement",
    "ConditionalStatement",
    "Condition",
    "RelationOperations",
    "Block",
    "AssignmentStatement",
    "InCrement",
    "Operand",
    "FunctionDeclaration",
    "ReturnType",
    "FunctionBody",
    "ReturnStatement",
    "Parameter",
    "function",
    "functionParam",
    "SwitchStatement",
    "SwitchExpression",
    "SwitchBody",
    "Case",
    "StructDec",
    "inStruct",
    "funCall",
    "Statement",
    "Statements",
    "Program",
    "void",
  };
}
/* JavaCC - OriginalChecksum=a849c6127caa2ae092d7dd4c7cf26dee (do not edit this line) */
