/* Generated By:JavaCC: Do not edit this line. GoVisitor.java Version 5.0 */
package com.bupt.ast;


public interface GoVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTone_line node, Object data);
  public Object visit(ASTsum node, Object data);
  public Object visit(ASTterm node, Object data);
  public Object visit(ASTunary node, Object data);
  public Object visit(ASTelement node, Object data);
  public Object visit(ASTDeclarationStatement node, Object data);
  public Object visit(ASTtype node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTAssignmentOperator node, Object data);
  public Object visit(ASTOneOperandOperator node, Object data);
  public Object visit(ASTIterationStatement node, Object data);
  public Object visit(ASTSimpleStatement node, Object data);
  public Object visit(ASTConditionalStatement node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTRelationOperations node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTAssignmentStatement node, Object data);
  public Object visit(ASTInCrement node, Object data);
  public Object visit(ASTOperand node, Object data);
  public Object visit(ASTFunctionDeclaration node, Object data);
  public Object visit(ASTReturnType node, Object data);
  public Object visit(ASTFunctionBody node, Object data);
  public Object visit(ASTReturnStatement node, Object data);
  public Object visit(ASTParameter node, Object data);
  public Object visit(ASTfunction node, Object data);
  public Object visit(ASTfunctionParam node, Object data);
  public Object visit(ASTSwitchStatement node, Object data);
  public Object visit(ASTSwitchExpression node, Object data);
  public Object visit(ASTSwitchBody node, Object data);
  public Object visit(ASTCase node, Object data);
  public Object visit(ASTStructDec node, Object data);
  public Object visit(ASTinStruct node, Object data);
  public Object visit(ASTfunCall node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTStatements node, Object data);
  public Object visit(ASTProgram node, Object data);
}
/* JavaCC - OriginalChecksum=a74291f5fe40dd2606a21ebd0a045710 (do not edit this line) */
